# Generated by Django 6.0.5 on 2026-05-31 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Groomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("qualification", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Groomer",
                "verbose_name_plural": "Groomers",
                "db_table": "groomers",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("full", "Full grooming"),
                            ("spa", "Spa"),
                            ("other", "Other"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("species", models.CharField(max_length=100)),
                ("breed", models.CharField(blank=True, default="", max_length=100)),
                (
                    "groomer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pets",
                        to="store.groomer",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, related_name="pets", to="store.service"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "db_table": "pets",
                "ordering": ["name"],
            },
        ),
    ]
