# Generated by Django 6.0.5 on 2026-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
                "db_table": "qualifications",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="groomer",
            name="qualification",
        ),
        migrations.AddField(
            model_name="groomer",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True, related_name="groomers", to="store.qualification"
            ),
        ),
    ]
